version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: godoc-mcp-darwin
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/server/main.go
  - id: godoc-mcp-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/server/main.go
  - id: godoc-mcp-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/godoc-mcp/main.go

archives:
  - format: "tar.gz"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
